#!/bin/sh
#################################################
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#################################################
# Apache 2 vhost adder
# Original made by Droxtor
# Version 1.2.1
# Usage: addsite yourdomaingoeshere.org
#################################################
        if [ `whoami` != root ]; then
            echo Please run this script as root or using sudo
            exit
        fi
	if [ "$1" = "" ]; then
		echo "Example: addsite foobar.org"
		exit
	else
	if [ ! -d /home/www/ ]; then
        echo " == Creating www in /home/"
        mkdir /home/www/
		chmod 0700 /home/www/
        chown -R www-data:www-data /home/www/
	fi
	if [ ! -d /home/www/htdocs/ ]; then
        echo " == Creating htdocs in /home/www/"
        mkdir /home/www/htdocs/
        chown -R www-data:www-data /home/www/htdocs/
	fi
	if [ ! -d /home/www/cgi-bin/ ]; then
        echo " == Creating cgi-bin in /home/www/"
        mkdir /home/www/cgi-bin/
        chown -R www-data:www-data /home/www/cgi-bin/
	fi
	if [ ! -d /home/www/logs/ ]; then
        echo " == Creating logs in /home/www/"
        mkdir /home/www/logs/
        chown -R www-data:www-data /home/www/logs/
	fi
mkdir /home/www/htdocs/$1 /home/www/logs/$1 /home/www/cgi-bin/$1
chown -R www-data:www-data /home/www/htdocs/$1
chown -R www-data:www-data /home/www/logs/$1
chown -R www-data:www-data /home/www/cgi-bin/$1
if [ -n "$2" ]; then
alias="ServerAlias $2"
fi
echo "<VirtualHost *:80>
       ServerAdmin admin@$1
       ServerName  $1
       $alias
       # Indexes + Directory Root.
       DirectoryIndex index.html index.php
       DocumentRoot /home/www/htdocs/$1/

       # CGI Directory
       ScriptAlias /cgi-bin/ /home/www/cgi-bin/$1/
       <Location /cgi-bin>
               Options +ExecCGI
       </Location>

       # Logfiles
       ErrorLog  /home/www/logs/$1/error.log
       CustomLog /home/www/logs/$1/access.log combined
</VirtualHost>" > /etc/apache2/sites-available/$1.conf
a2ensite $1 >/dev/null 2>&1 &
/etc/init.d/apache2 reload >/dev/null 2>&1 &
fi
echo " == Added $1 succesfully! =="
