#!/bin/sh
#################################################
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#################################################
# Apache 2 vhost deleter
# Original made by Droxtor
# Version 1.2
# Usage: delsite yourdomaingoeshere.org
#################################################
if [ `whoami` != root ]; then
            echo Please run this script as root or using sudo
            exit
        fi
if [ "$1" = "" ]; then
echo "Example: delsite foobar.org"
exit
fi
a2dissite $1 &>/dev/null
read -p "Remove files? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
rm -r /home/www/htdocs/$1 /home/www/logs/$1 /home/www/cgi-bin/$1
fi
rm /etc/apache2/sites-available/$1.conf
/etc/init.d/apache2 reload &>/dev/null
echo " == Deleted $1 succesfully! =="
