#!/bin/sh
#################################################
#
# The MIT License (MIT)
#
# Copyright (c) 2014-2015 Robert Nevanen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# he above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#################################################
# Apache 2 vhost deleter
# Original made by Droxtor
# Version 1.2
# Usage: delsite yourdomaingoeshere.org
#################################################
if [ `whoami` != root ]; then
            echo Please run this script as root or using sudo
            exit
        fi
if [ "$1" = "" ]; then
echo "Example: delsite foobar.org"
exit
fi
a2dissite $1 &>/dev/null
read -p "Remove files? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
rm -r /home/www/htdocs/$1 /home/www/logs/$1 /home/www/cgi-bin/$1
fi
rm /etc/apache2/sites-available/$1.conf
/etc/init.d/apache2 reload &>/dev/null
echo " == Deleted $1 succesfully! =="
